<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Anggerik (Aras 6)',
            'nama_panjang' => 'Bilik Anggerik (Aras 6)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik APEC (Aras 13)',
            'nama_panjang' => 'Bilik APEC (Aras 13)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik ASEAN (Aras 18)',
            'nama_panjang' => 'Bilik ASEAN (Aras 18)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Bunga Raya (Aras 31)',
            'nama_panjang' => 'Bilik Bunga Raya (Aras 31)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Cempaka (Aras 27)',
            'nama_panjang' => 'Bilik Cempaka (Aras 27)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik COMCEC (Aras 19)',
            'nama_panjang' => 'Bilik COMCEC (Aras 19)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '7',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Dahlia (Aras 31)',
            'nama_panjang' => 'Bilik Dahlia (Aras 31)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Kenanga (Aras 28)',
            'nama_panjang' => 'Bilik Kenanga (Aras 28)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Latihan (Aras 19)',
            'nama_panjang' => 'Bilik Latihan (Aras 19)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '7',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Latihan (Aras 2)',
            'nama_panjang' => 'Bilik Latihan (Aras 2)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Lily (Aras 23)',
            'nama_panjang' => 'Bilik Lily (Aras 23)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mawar (Aras 30)',
            'nama_panjang' => 'Bilik Mawar (Aras 30)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Melur (Aras 26)',
            'nama_panjang' => 'Bilik Melur (Aras 26)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik OECD (Aras 21)',
            'nama_panjang' => 'Bilik OECD (Aras 21)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik OIC (Aras 12)',
            'nama_panjang' => 'Bilik OIC (Aras 12)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 25)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 25)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 19)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 19)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '7',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan Aras 20',
            'nama_panjang' => 'Bilik Perbincangan Aras 20',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Sakura (Aras 31)',
            'nama_panjang' => 'Bilik Sakura (Aras 31)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Seminar 1',
            'nama_panjang' => 'Bilik Seminar 1',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik Seminar 2',
            'nama_panjang' => 'Bilik Seminar 2',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik UNCTAD (Aras 17)',
            'nama_panjang' => 'Bilik UNCTAD (Aras 17)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik UNIDO (Aras 8)',
            'nama_panjang' => 'Bilik UNIDO (Aras 8)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        DB::table('Rooms')->insert([
            'nama' => 'Bilik WEF (Aras 15)',
            'nama_panjang' => 'Bilik WEF (Aras 15)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik WIEF (Aras 22)',
            'nama_panjang' => 'Bilik WIEF (Aras 22)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik WTO (Aras 14)',
            'nama_panjang' => 'Bilik WTO (Aras 14)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Break Out Room (Aras 11)',
            'nama_panjang' => 'Break Out Room (Aras 11)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Break Out Room (Aras 19)',
            'nama_panjang' => 'Break Out Room (Aras 19)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Break Out Room (Aras 25)',
            'nama_panjang' => 'Break Out Room (Aras 25)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Break Out Room (Aras 4)',
            'nama_panjang' => 'Break Out Room (Aras 4)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Dewan Makan Saffron (Aras 31)',
            'nama_panjang' => 'Dewan Makan Saffron (Aras 31)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Dewan Perdana',
            'nama_panjang' => 'Dewan Perdana',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'is_upload' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'VIP Holding Room',
            'nama_panjang' => 'VIP Holding Room',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'Y',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);

        //biru
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat Kewangan (Aras 24)',
            'nama_panjang' => 'Bilik Mesyuarat Kewangan (Aras 24)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat Pejabat Timbalan Menteri (Aras 29)',
            'nama_panjang' => 'Bilik Mesyuarat Pejabat Timbalan Menteri (Aras 29)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat PKDS (Aras 10)',
            'nama_panjang' => 'Bilik Mesyuarat PKDS (Aras 10)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat PUU (Aras 27)',
            'nama_panjang' => 'Bilik Mesyuarat PUU (Aras 27)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat TKSU (I) (Aras 27)',
            'nama_panjang' => 'Bilik Mesyuarat TKSU (I) (Aras 27)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat TKSU (P) (Aras 28)',
            'nama_panjang' => 'Bilik Mesyuarat TKSU (P) (Aras 28)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Mesyuarat TKSU (PB) (Aras 28)',
            'nama_panjang' => 'Bilik Mesyuarat TKSU (PB) (Aras 28)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 10)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 10)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 11)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 11)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 13)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 13)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 3)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 3)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 5)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 5)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 8)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 8)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan (Aras 9)',
            'nama_panjang' => 'Bilik Perbincangan (Aras 9)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'N',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan KSU (Aras 28)',
            'nama_panjang' => 'Bilik Perbincangan KSU (Aras 28)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik Perbincangan PKRP (Aras 14)',
            'nama_panjang' => 'Bilik Perbincangan PKRP (Aras 14)',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
        DB::table('Rooms')->insert([
            'nama' => 'Bilik KSU',
            'nama_panjang' => 'Bilik KSU',
            'nama_petugas' => 'Ahmad b. Ali',
            'no_tel_petugas' => '017-11122231',
            'department_id' => '8',
            'aras' => '23',
            'kapasiti' => '0',
            'is_auto' => 'N',
            'is_projector' => 'Y',
            'is_equipment' => 'Y',
            'keterangan' => '-',
            'status' => '1',
            'created_by' => '1',
        ]);
    }
}
